# Exported from Render on 2024-05-09T15:35:53Z
services:
- type: web
  name: hastebin
  runtime: docker
  repo: https://github.com/VijayakumarRavi/haste-server
  plan: free
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
